export const LOGIN = 'LOGIN';
export const MOSTRAR_USUARIO = 'MOSTRAR_USUARIO';
export const OBTENER_DOCUMENTOS = 'OBTENER_DOCUMENTOS';
export const MOSTRAR_DOCUMENTOS = 'MOSTRAR_DOCUMENTOS';
export const GUARDAR_DOCUMENTO = 'GUARDAR_DOCUMENTO';
export const ELIMINAR_DOCUMENTO = 'ELIMINAR_DOCUMENTO';

//docuemntos Aceptados
export const OBTENER_DOCUMENTOS_ACEPTADOS = 'OBTENER_DOCUMENTOS_ACEPTADOS';
export const MOSTRAR_DOCUMENTOS_ACEPTADOS = 'MOSTRAR_DOCUMENTOS_ACEPTADOS';

// docuementos rechazados
export const OBTENER_DOCUMENTOS_RECHAZADOS = 'OBTENER_DOCUMENTOS_RECHAZADOS';
export const MOSTRAR_DOCUMENTOS_RECHAZADOS = 'MOSTRAR_DOCUMENTOS_RECHAZADOS';

// docuementos por revisar
export const OBTENER_DOCUMENTOS_POR_REVISAR = 'OBTENER_DOCUMENTOS_POR_REVISAR';
export const MOSTRAR_DOCUMENTOS_POR_REVISAR = 'MOSTRAR_DOCUMENTOS_POR_REVISAR';
export const ELIMINAR_DOCUMENTO_POR_REVISAR = 'ELIMINAR_DOCUMENTO_POR_REVISAR';

// reportes
export const OBTENER_REPORTES = 'OBTENER_REPORTES';
export const MOSTRAR_REPORTES = 'MOSTRAR_REPORTES';