export const LOGIN = 'LOGIN';
export const MOSTRAR_USUARIO = 'MOSTRAR_USUARIO';
export const OBTENER_DOCUMENTOS = 'OBTENER_DOCUMENTOS';
export const MOSTRAR_DOCUMENTOS = 'MOSTRAR_DOCUMENTOS';
export const GUARDAR_DOCUMENTO = 'GUARDAR_DOCUMENTO';

//docuemntos Aceptados
export const OBTENER_DOCUMENTOS_ACEPTADOS = 'OBTENER_DOCUMENTOS_ACEPTADOS';
export const MOSTRAR_DOCUMENTOS_ACEPTADOS = 'MOSTRAR_DOCUMENTOS_ACEPTADOS';
